package com.omnilabs.omfiles.core.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors — exact palette from the premium HTML mockup
val md_theme_light_primary = Color(0xFF003d9b)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFF0052cc)
val md_theme_light_onPrimaryContainer = Color(0xFFc4d2ff)
val md_theme_light_secondary = Color(0xFF5c5f60)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFdee0e2)
val md_theme_light_onSecondaryContainer = Color(0xFF606365)
val md_theme_light_tertiary = Color(0xFF003e96)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFF2356b5)
val md_theme_light_onTertiaryContainer = Color(0xFFc3d2ff)
val md_theme_light_error = Color(0xFFba1a1a)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_errorContainer = Color(0xFFffdad6)
val md_theme_light_onErrorContainer = Color(0xFF93000a)
val md_theme_light_background = Color(0xFFf9f9ff)
val md_theme_light_onBackground = Color(0xFF041b3c)
val md_theme_light_surface = Color(0xFFf9f9ff)
val md_theme_light_onSurface = Color(0xFF041b3c)
val md_theme_light_surfaceVariant = Color(0xFFd7e2ff)
val md_theme_light_onSurfaceVariant = Color(0xFF434654)
val md_theme_light_surfaceDim = Color(0xFFcadaff)
val md_theme_light_surfaceBright = Color(0xFFf9f9ff)
val md_theme_light_surfaceContainerLowest = Color(0xFFffffff)
val md_theme_light_surfaceContainerLow = Color(0xFFf1f3ff)
val md_theme_light_surfaceContainer = Color(0xFFe8edff)
val md_theme_light_surfaceContainerHigh = Color(0xFFe0e8ff)
val md_theme_light_surfaceContainerHighest = Color(0xFFd7e2ff)
val md_theme_light_outline = Color(0xFF737685)
val md_theme_light_outlineVariant = Color(0xFFc3c6d6)
val md_theme_light_inverseSurface = Color(0xFF1d3052)
val md_theme_light_inverseOnSurface = Color(0xFFedf0ff)
val md_theme_light_inversePrimary = Color(0xFFb2c5ff)
val md_theme_light_surfaceTint = Color(0xFF0c56d0)

// Dark Theme Colors — derived from the light palette for consistency
val md_theme_dark_primary = Color(0xFFb2c5ff)
val md_theme_dark_onPrimary = Color(0xFF001848)
val md_theme_dark_primaryContainer = Color(0xFF0040a2)
val md_theme_dark_onPrimaryContainer = Color(0xFFdae2ff)
val md_theme_dark_secondary = Color(0xFFc5c6c8)
val md_theme_dark_onSecondary = Color(0xFF191c1e)
val md_theme_dark_secondaryContainer = Color(0xFF444749)
val md_theme_dark_onSecondaryContainer = Color(0xFFe1e2e4)
val md_theme_dark_tertiary = Color(0xFFb1c6ff)
val md_theme_dark_onTertiary = Color(0xFF001946)
val md_theme_dark_tertiaryContainer = Color(0xFF00419d)
val md_theme_dark_onTertiaryContainer = Color(0xFFd9e2ff)
val md_theme_dark_error = Color(0xFFffb4ab)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000a)
val md_theme_dark_onErrorContainer = Color(0xFFffdad6)
val md_theme_dark_background = Color(0xFF041b3c)
val md_theme_dark_onBackground = Color(0xFFedf0ff)
val md_theme_dark_surface = Color(0xFF041b3c)
val md_theme_dark_onSurface = Color(0xFFedf0ff)
val md_theme_dark_surfaceVariant = Color(0xFF1d3052)
val md_theme_dark_onSurfaceVariant = Color(0xFFc3c6d6)
val md_theme_dark_surfaceDim = Color(0xFF041b3c)
val md_theme_dark_surfaceBright = Color(0xFF37506d)
val md_theme_dark_surfaceContainerLowest = Color(0xFF041332)
val md_theme_dark_surfaceContainerLow = Color(0xFF0a1f45)
val md_theme_dark_surfaceContainer = Color(0xFF11264c)
val md_theme_dark_surfaceContainerHigh = Color(0xFF1b3158)
val md_theme_dark_surfaceContainerHighest = Color(0xFF263c63)
val md_theme_dark_outline = Color(0xFF737685)
val md_theme_dark_outlineVariant = Color(0xFF434654)
val md_theme_dark_inverseSurface = Color(0xFFf9f9ff)
val md_theme_dark_inverseOnSurface = Color(0xFF041b3c)
val md_theme_dark_inversePrimary = Color(0xFF003d9b)
val md_theme_dark_surfaceTint = Color(0xFFb2c5ff)

// File type colors — kept as utility swatches
val fileTypeFolder = Color(0xFFFFC107)
val fileTypeImage = Color(0xFF4CAF50)
val fileTypeVideo = Color(0xFFF44336)
val fileTypeAudio = Color(0xFF9C27B0)
val fileTypeArchive = Color(0xFFFF9800)
val fileTypeApk = Color(0xFF2196F3)
val fileTypeDocument = Color(0xFF5B9BD5)
val fileTypeDefault = Color(0xFF9E9E9E)
